import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
const code=fs.readFileSync(new URL('../extension/browser-content.js',import.meta.url),'utf8');
function setup({reject=false,skip=false}={}){
 const handlers={},messages=[],timers=[];let listener,clock=0;
 const video={currentTime:0,muted:false,paused:true,duration:120,seekable:{length:1},readyState:2,seeking:false,videoWidth:640,videoHeight:360,isConnected:true,currentSrc:'blob:test',textTracks:[],playbackRate:1,clientWidth:640,clientHeight:360,addEventListener(n,f){handlers[n]=f;},pause(){this.paused=true;},async play(){this.paused=false;handlers.play?.();}};
 const elements=[];const element=()=>({style:{},append(){},attachShadow(){return {append(){}};},remove(){this.removed=true;}});
 const context={console,performance:{now:()=>++clock},location:{hostname:'www.youtube.com',href:'https://www.youtube.com/watch?v=test',pathname:'/watch'},URL,setTimeout,clearTimeout,setInterval(f){timers.push(f);},document:{hidden:false,documentElement:{append(e){elements.push(e);}},querySelector(s){return s==='video'?video:null;},querySelectorAll(){return [video];},createElement(type){if(type==='canvas')return {getContext:()=>({drawImage(){}}),toDataURL:()=> 'data:image/jpeg;base64,AAA'};return element();}},chrome:{runtime:{onMessage:{addListener(f){listener=f;}},async sendMessage(m){messages.push(m);if(m.op==='state')return {ok:true,value:{armed:false}};if(m.op==='analyze'){if(reject)return {ok:false,error:'Provider rejected request'};return {ok:true,value:m.batch.map(b=>({start_time:b.start_time,end_time:b.end_time,decision:skip&&b.start_time===0?'skip':'keep'}))};}return {ok:true};}}}};
 vm.runInNewContext(code,context);return {video,messages,elements,timers,start(){listener({op:'start'},{},()=>{});},stop(){listener({op:'stop'},{},()=>{});}};
}
async function drain(){for(let i=0;i<15;i++)await new Promise(r=>setImmediate(r));}
test('v8 samples the extended horizon in bounded batches before unmuting and playing',async()=>{const x=setup();x.start();await x.video.play();await drain();assert.equal(x.messages.filter(m=>m.op==='analyze').length,20);assert.equal(x.video.currentTime,0);assert.equal(x.video.muted,false);assert.equal(x.video.paused,false);assert(x.elements.every(e=>e.removed));assert.equal(x.messages.filter(m=>m.op==='analyze')[0].batch[0].frames.length,4);});
test('v8 provider rejection leaves video covered, muted and paused at original position',async()=>{const x=setup({reject:true});x.start();await x.video.play();await drain();assert.equal(x.video.paused,true);assert.equal(x.video.muted,true);assert.equal(x.video.currentTime,0);assert(x.elements.some(e=>!e.removed));});
test('v8 initial skip is applied before revealing the player',async()=>{const x=setup({skip:true});x.start();await x.video.play();await drain();assert.equal(x.video.currentTime,2);assert.equal(x.video.paused,false);});
test('v8 stop invalidates work and leaves playback paused',async()=>{const x=setup();x.start();await x.video.play();x.stop();await drain();assert.equal(x.video.paused,true);assert.equal(x.video.muted,false);assert(!x.messages.some(m=>m.status?.startsWith('Active')));});
